#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConsts {
    uint batch;
    uint features;
} pc;

layout(binding = 0, std430) readonly buffer InputBuf {
    float x[];   // column-major: x[c * batch + r]
};

layout(binding = 1, std430) writeonly buffer RowRmsSqBuf {
    float row_rms_sq[]; // размер batch
};

void main() {
    uint r = gl_GlobalInvocationID.x;
    if (r >= pc.batch) return;

    float sum_sq = 0.0;
    for (uint c = 0; c < pc.features; c++) {
        float val = x[c * pc.batch + r];
        sum_sq += val * val;
    }
    float mean_sq = sum_sq / float(pc.features);

    row_rms_sq[r] = mean_sq;
}