#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConsts {
    uint rows;
    uint cols;
} pc;

layout(binding = 0, std430) readonly buffer GradOutBuf {
    float go[]; // go[r]
};

layout(binding = 1, std430) writeonly buffer GradInBuf {
    float gi[]; // gi[c * rows + r]
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    uint total = pc.rows * pc.cols;
    if (idx >= total) return;

    uint r = idx % pc.rows;
    gi[idx] = go[r];
}