#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConsts {
    float beta;
    uint total;
} pc;

layout(binding = 0, std430) buffer GradBuf {
    float grads[];
};
layout(binding = 1, std430) buffer StateBuf {
    float state[];
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pc.total) return;
    float v_old = state[i];
    float v_new = pc.beta * v_old + grads[i];
    grads[i] = pc.beta * v_new + grads[i];
    state[i] = v_new;
}