#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConsts {
    uint total;
} pc;

layout(binding = 0, std430) readonly buffer InA {
    float a[];
};
layout(binding = 1, std430) readonly buffer InB {
    float b[];
};
layout(binding = 2, std430) writeonly buffer Out {
    float o[];
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pc.total) return;
    o[i] = a[i] * b[i];
}