#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConsts {
    uint total;
} pc;

layout(binding = 0, std430) readonly buffer InputBuf {
    float x[];
};

layout(binding = 1, std430) readonly buffer LambdaBuf {
    float lambda; // единственное значение
};

layout(binding = 2, std430) writeonly buffer OutputBuf {
    float y[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= pc.total) return;

    float x_val = x[idx];
    float sp = log(1.0 + exp(x_val));
    float tanh_sp = tanh(lambda * sp);
    y[idx] = x_val * tanh_sp;
}