#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConsts {
    uint total;
    uint features;       // in_features == out_features
    float alpha;
} pc;

layout(binding = 0, std430) readonly buffer InputBuf {
    float x[];
};
layout(binding = 1, std430) readonly buffer MinBuf {
    float min_vals[];    // длина features
};
layout(binding = 2, std430) readonly buffer MaxBuf {
    float max_vals[];
};
layout(binding = 3, std430) writeonly buffer OutputBuf {
    float y[];
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pc.total) return;

    uint c = i % pc.features;
    float x_val = x[i];
    float min_v = min_vals[c];
    float max_v = max_vals[c];
    float d_min = abs(x_val - min_v);
    float d_max = abs(x_val - max_v);
    float closest = (d_min <= d_max) ? min_v : max_v;
    y[i] = x_val + pc.alpha * (closest - x_val);
}